### ISSUE TITLE
Not possible to set mount owner

### ISSUE THREAD

**Issue by phlegx** [ContainX/docker-volume-netshare#121]
Hi there,

I'm trying to setup an external cifs mount (netshare version 0.32) via `docker volume` like:

```docker volume create -d cifs --name xxxx.example.com/backup/elasticsearch --opt username=username --opt password=password --opt domain=xxxx.example.com --opt uid=1000 --opt gid=1000```

In my docker compose file I include it like that:

```
elasticsearch:
  ..
  ..
  volumes:
    - backup_elasticsearch:/backup/elasticsearch

volumes:
  backup_elasticsearch:
    external:
      name:  xxxx.example.com/backup/elasticsearch
``` 

The owner however inside the container is `148700`, an user id that does not even exist in my container:

```
  File: /backup/elasticsearch
  Size: 0         	Blocks: 0          IO Block: 16384  directory
Device: 60h/96d	Inode: 281         Links: 2
Access: (0755/drwxr-xr-x)  Uid: (148700/ UNKNOWN)   Gid: (148700/ UNKNOWN)
Access: 2017-04-19 08:53:36.000000000
Modify: 2017-04-20 14:47:08.000000000
Change: 2017-04-20 14:47:08.000000000
```
Is setting the owner simply not possible or am I doing something wrong here?
