### ISSUE TITLE
Docker-compose docs?

### ISSUE THREAD

**Issue by dbsanfte** [ContainX/docker-volume-netshare#125]
Are there any?

I see people doing things with cifs in their docker-compose like:

> volumes:
>    data:
>       driver: cifs
>       driver_opts:
>          share: host.domain/share-name
>          username: someuser
>          password: somepassword

The username and password options in the docker-compose aren't passed to the driver, though. They don't work. Only passing the username and password on the command line when starting the driver seems to. Otherwise I just get "mount exited with return code: 32".

I want to specify the username and password in configuration, not on the command line.

**Comment by pablolibo** [comment]
I hope this could help you: http://netshare.containx.io/docs/cifs

**Comment by dbsanfte** [comment]
Thanks. Looks like the username/password aren't being passed down to the driver though via my docker compose file. The only way it works is specifying creds on the command-line of the driver manually.

**Comment by jdessey** [comment]
I can confirm that from command line:
`docker volume create -d cifs --name vol1 -o share=host/sharename,username=***,password=***`
works, as the username and password args are reflected in the plugin's mount execution (with --verbose flag).

> DEBU[0873] Executing: mount -t cifs -o username=test,password=***,rw //host/sharename /var/lib/docker-volumes/netshare/cifs/vol1

But with compose file:
```
volumes:
    cifs-test-share:
      driver: cifs
      driver_opts:
        share: "host/sharename,username=test,password=test"
```
or
```
volumes:
    cifs-test-share:
      driver: cifs
      driver_opts:
        share: host/sharename
        username: test
        password: test
```

credentials are not passed through. (guest,rw appear to be default)

> DEBU[0485] Executing: mount -t cifs -o guest,rw //host/sharename /var/lib/docker-volumes/netshare/cifs/storagetest_cifs-test-share
> 2017/07/26 15:28:56 mount: mounting //host/sharename on /var/lib/docker-volumes/netshare/cifs/storagetest_cifs-test-share failed: Invalid argument
