### ISSUE TITLE
Fail to list volumes after stopping docker-volume-netshare

### ISSUE THREAD

**Issue by krg7880** [ContainX/docker-volume-netshare#150]
**Docker Version**
17.09.0-ce, build afdb6d4

**Docker-Volume-Netshare Version**
0.34 (docker-volume-netshare_0.34_linux_amd64-bin)

**Issue**
Attempted to mount EFS using the configuration below. After getting an error several times, I stopped the `docker-volume-netshare` daemon and attempted to do `docker volume ls` and the command simply hangs.  Other docker commands seems to work, however... _(ie: `docker container ls`)_

**Error**
```
container failed: error while mounting volume '/': VolumeDriver.Mount: exit status 32"  
```

**Compose Config**
```
version: "3.2"

volumes:
  data_portainer:
    driver: nfs
    driver_opts:
      share: <EFS_DNS>:/
      o: "port=2049"
          
services:
  ui: 
    image: portainer/portainer:1.15.5
    ports:
      - "9000:9000"
    volumes:
      - type: volume
        source: data_portainer
        target: /data
      - type: bind 
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources: 
          limits:
            cpus: "0.25"
            memory: 100M
          reservations:
            cpus: "0.25"
            memory: 50M
    command: ["-H", "unix:///var/run/docker.sock"]
```
