### ISSUE TITLE
Failed to mount NFS Volume when using Docker-Compose

### ISSUE THREAD

**Issue by chkelly** [ContainX/docker-volume-netshare#64]
I was able to use compose to startup my first container with an NFS mount without issue. Here is my compose file:

```
version: '2'
services:
  deluge:
    image: linuxserver/deluge
    restart: always
    environment:
      - PGID=65534
      - PUID=65534
    volumes:
      - deluge-config:/config
      - deluge-downloads:/downloads
volumes:
  deluge-config:
    driver: local
   deluge-downloads:
    driver: nfs
    driver_opts:
      share: "some-host:/data/path"
```

I can see the volume..
```
docker volume ls
DRIVER              VOLUME NAME
local               dockerdeluge_deluge-config
nfs                 dockerdeluge_deluge-downloads
```
This worked great. So I went to spinup a second container with a couple of NFS volume mappings...

```
version: '2'
services:
  sonarr:
    image: tuxeh/sonarr:latest
    restart: always
    volumes:
      - sonarr-config:/volumes/config
      - sonarr-completed:/volumes/completed
      - sonarr-media:/volumes/media
volumes:
  sonarr-config:
    driver: local
  sonarr-completed:
    driver: nfs
    driver_opts:
      share: "some-host:/data/path"
  sonarr-media:
    driver: nfs
    driver_opts:
      share: "some-host:/data/path/2"
```

When I docker-compose up -d on the same docker host:

```
Creating volume "dockersonarr_sonarr-completed" with nfs driver
Creating volume "dockersonarr_sonarr-media" with nfs driver
Creating dockersonarr_sonarr_1

ERROR: for sonarr  Cannot create container for service sonarr: VolumeDriver.Mount: exit status 32
ERROR: Encountered errors while bringing up the project.
```

The log just showed it getting mounted and then unmounted.

So the first thing I did was edit /etc/default/docker-volume-netshare and changed DKV_NETSHARE_OPTS="nfs" to DKV_NETSHARE_OPTS="nfs --verbose" and restarted the service.

Interestingly enough, the output of docker volume ls doesnt show our nfs volume anymore (although on the host its still mounted, and deluge is still happily writing to it) so possibly this is a second bug?

```
time="2016-08-05T10:44:16-04:00" level=debug msg="Entering List: { map[]}"
```

So I attempted to docker-compose up -d again receiving the same error however this is whats in the logs.

```
time="2016-08-05T10:48:50-04:00" level=debug msg="Entering Get: {dockersonarr_sonarr-completed map[]}"
time="2016-08-05T10:48:50-04:00" level=debug msg="Host path for dockersonarr_sonarr-completed is at /var/lib/docker-volumes/netshare/nfs/dockersonarr_sonarr-completed"
time="2016-08-05T10:48:50-04:00" level=debug msg="Entering Get: {dockersonarr_sonarr-media map[]}"
time="2016-08-05T10:48:50-04:00" level=debug msg="Entering Mount: {dockersonarr_sonarr-completed map[]}"
time="2016-08-05T10:48:50-04:00" level=info msg="Mounting NFS volume dockersonarr_sonarr-completed: on /var/lib/docker-volumes/netshare/nfs/dockersonarr_sonarr-completed"
time="2016-08-05T10:48:50-04:00" level=debug msg="Mounting with NFSv4 - src: dockersonarr_sonarr-completed:, dest: /var/lib/docker-volumes/netshare/nfs/dockersonarr_sonarr-completed"
time="2016-08-05T10:48:50-04:00" level=debug msg="exec: mount -v -t nfs4 dockersonarr_sonarr-completed: /var/lib/docker-volumes/netshare/nfs/dockersonarr_sonarr-completed\n"
2016/08/05 10:48:50 mount.nfs4: Failed to resolve server dockersonarr_sonarr-completed: Name or service not known
```

Notice that its oddly trying to resolve the volume name as the nfs host? Whats interesting is that I downed the deluge service that worked before, deleted the volume and attempted to up -d and saw the exact same results. I couldnt mount the NFS volume anymore.

Any thoughts?
